### ISSUE TITLE
Creating users

### ISSUE THREAD

**Issue by gobfink** [gobfink/AcronymDB#3]
On the assett hosted VM i had an issue registering a user. 
Here's the error - 
sqlalchemy.exc.OperationalError

sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1292, "Incorrect datetime value: '0' for column 'userLoginDT' at row 1")
[SQL: INSERT INTO `tbl_User` (`userEmail`, username, `userFN`, `userLN`, `userPasswordHash`, `userIsAdmin`, `userLastLoginDT`, `userLoginDT`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('jayden.rosier@assett.net', 'jadylocks', 'Jayden', 'Rosier', 'pbkdf2:sha256:150000$rlOpN0Sd$e492903534a4a7b06a5dadd8aa47c21413a81125edfd8c6126a333d681c1c0c8', 0, datetime.datetime(2019, 10, 28, 20, 35, 11, 944014), False)]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last)

    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context

    cursor, statement, parameters, context

    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute

    cursor.execute(statement, parameters)

    File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute

    res = self._query(query)

    File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query

    db.query(q)

    File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 226, in query

    _mysql.connection.query(self, query)

    The above exception was the direct cause of the following exception:
    File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__

    return self.wsgi_app(environ, start_response)

    File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app

**Comment by gobfink** [comment]
Fixed this issue with null in the login times
